project/urls.py
from django.conf.urls import url
from project import views


urlpatterns = [
    url(r'^index$', views.index,name='index'),
    url(r'^register$', views.register),
    url(r'^register_check$', views.register_check),
    url(r'^login$', views.login),
    url(r'^login_check$', views.login_check),
    url(r'^show_msg$', views.show_msg),
    url(r'^html_escape$', views.html_escape),
    url(r'^02$',views.zero_two,name='02'),
    url(r'^url_reverse$',views.url_reverse),
    url(r"^show_args/(\d+)/(\d+)$",views.show_args,name='show_args'),
    url(r"^show_kwargs/(?P<c>\d+)/(?P<d>\d+)$",views.show_kwargs,name='show_kwargs'),
    url(r'^test_rediret$',views.test_rediret),
    url(r'^page/(?P<pindex>[0-9]*)$',views.area),
    url(r'^area1$',views.area1),
    url(r'^area2$',views.area2),
    url(r'^area3_(\d+)$',views.area3),
]

web/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('project.urls',namespace='booktest')),
]

project/models.py
from django.db import models


# Create your models here.
class UserInfo(models.Model):
    name = models.CharField(max_length=20)
    password = models.CharField(max_length=20)
    email = models.CharField(max_length=20)
    phone = models.CharField(max_length=20)

class AreaInfo(models.Model):
    atitle = models.CharField(max_length=20)
    pid = models.IntegerField(null=True)

project/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from project.models import UserInfo, AreaInfo


# Create your views here.
def index(request):
    return render(request, 'index.html')


def register(request):
    return render(request, 'register.html')


def register_check(request):
    name = request.POST.get('username')
    pwd = request.POST.get('pwd')
    email = request.POST.get('email')
    phone = request.POST.get('phone')
    # warn_data = 1
    try:
        UserInfo.objects.get(name=name)
        return HttpResponse('用户名重复')
        # return render(request, 'register.html', {'warn_data': warn_data})
    except:
        usr = UserInfo()
        usr.name = name
        usr.password = pwd
        usr.email = email
        usr.phone = phone
        usr.save()
        return render(request, 'register_check.html')


def login(request):
    if 'usr' in request.COOKIES:
        username = request.COOKIES['usr']
    else:
        username = ""
    return render(request, 'login.html', {'username': username})


def login_check(request):
    username = request.POST.get('username')
    pwd = request.POST.get('pwd')
    rem_name = request.POST.get('rem_name')
    try:
        usr = UserInfo.objects.get(name=username)
        if pwd == usr.password:
            response = redirect('/show_msg')
            request.session['usr'] = username
            # response.set_cookie('usr', username)
            # response = JsonResponse({'res': 1}) ajax
            if rem_name == 'on':
                # request.session['usr'] = username
                response.set_cookie('usr', username)
                # return render(request, 'login_check.html') 表单实现
            return response

        else:
            return redirect('/login')
            # return JsonResponse({'res': 2})
    except:
        # return HttpResponse('用户名或密码错误')
        return redirect('/login')


def show_msg(request):
    try:
        username = request.session.get('usr')
        # username = request.COOKIES['usr']
        UserMsg = UserInfo.objects.get(name=username)
        phone = UserMsg.phone
        email = UserMsg.email
        content = {'username': username, 'phone': phone, 'email': email}
        return render(request, 'show_msg.html', content)
    except:
        return redirect('/login')


def html_escape(request):
    context = {'content': '<h1>hello world</h1>'}
    return render(request, 'html_escape.html', context)


def zero_two(request):
    print(request.META['REMOTE_ADDR'])
    return render(request, '02.html')


def url_reverse(request):
    return render(request, 'url_reverse.html')


def show_args(request, a, b):
    return HttpResponse(a + ":" + b)


def show_kwargs(request, c, d):
    return HttpResponse(c + ":" + d)


from django.core.urlresolvers import reverse


def test_rediret(request):
    # return redirect('/02')
    url = reverse('booktest:show_kwargs', kwargs={'c': 3, 'd': 4})
    return redirect(url)


from django.core.paginator import Paginator


def area(request, pindex):
    list1 = AreaInfo.objects.filter(pid__isnull=True)
    p = Paginator(list1, 10)
    if pindex == '':
        pindex = '1'
    pindex = int(pindex)
    list2 = p.page(pindex)
    plist = p.page_range
    content = {'list': list2, 'plist': plist, 'pindex': pindex}
    return render(request, 'area.html', content)


def area1(request):
    return render(request, 'area1.html')


def area2(request):
    list = AreaInfo.objects.filter(pid__isnull=True)
    list2 = []
    for item in list:
        list2.append([item.id, item.atitle])
    return JsonResponse({'data': list2})


def area3(request, parent_id):
    list = AreaInfo.objects.filter(pid = parent_id)
    list2 = []
    for item in list:
        list2.append([item.id, item.atitle])
    return JsonResponse({'data': list2})

templates/02.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<img src="/static/images/IMG_1500.JPG">
<img src="/static/images/IMG_1501.JPG">
<img src="/static/images/IMG_1502.png">
</body>
</html>

templates/area.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <ul>
    {% for area in list %}
        <li>{{ area.atitle }}</li>
    {% endfor %}
    </ul>
    {% for index in plist %}
        {% if pindex == index %}
            {{ pindex }}
        {% else %}
            <a href="/page/{{ index }}">{{ index }}</a>
        {% endif %}
    {% endfor %}
</body>
</html>

templates/area1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>省市区</title>
    <script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
    <script type="text/javascript">
        $(function () {
            $.get('/area2',function (dic) {
                pro =$ ('#pro')
                $.each(dic.data, function (index, item) {
                    pro.append('<option value='+item[0]+'>'+item[1]+'</option>')
                })
            })
            $('#pro').change(function () {
                $.get('/area3_'+$(this).val(),function (dic) {
                    city=$("#city")
                    city.empty().append('<option value="">请选择市</option>')
                    dis=$("#dis")
                    dis.empty().append('<option value="">请选择区县</option>')
                    $.each(dic.data, function (index, item) {
                        city.append('<option value='+item[0]+'>'+item[1]+'</option>')
                    })
                })
            })

            $('#city').change(function () {
                $.get('/area3_'+$(this).val(), function (dic) {
                    dis=$("#dis")
                    dis.empty().append('<option value="">请选择区县</option>')
                    $.each(dic.data, function (index, item) {
                        dis.append('<option value='+item[0]+'>'+item[1]+'</option>')
                    })
                })
            })
        })
    </script>
</head>

<body>
<select id="pro">
    <option value="">请选择省</option>
</select>
<select id="city">
    <option value="">请选择市</option>
</select>
<select id="dis">
    <option value="">请选择区县</option>
</select>

</body>
</html>

templates/git_test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>git_test</title>
</head>
<body>
<h1>git_test</h1>
</body>
</html>

templates/html_escape.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {{ content|safe }}
    {% autoescape off%}
    {{ content }}
        {{ content }}
    {% endautoescape %}
    {{ data|default:'<b>hello</b>' }}
    {{data|default:"&lt;b&gt;123&lt;/b&gt;"}}
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
</head>
<body>
    <h1>首页</h1>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
</head>
<script src="/static/js/jquery-1.12.4.min.js"></script>
<script>
    $(function () {
        $("#ajaxBtn").click(function () {
            var username = $("#username").val(),
            pwd = $("#pwd").val(),
            rem_name = $("#rem_name").val();

            $.ajax({
                'url':'/login_check',
                'data':{'username':username,'pwd':pwd,'rem_name':rem_name},
                'type':'post',
                'dataType':'json'
            })
                .done(function (data) {
                    if (data.res == 1){
                        $("#loginmsg").show().html("登录成功")
                        {#location.href = '/show'#}
                    }
                    if (data.res == 2){
                         $("#loginmsg").show().html("账户名或密码错误")
                        location.href = '/login'
                    }
            })
        })
    })
</script>
<body>
<form action="/login_check" method="post">
    {% csrf_token %}
    用户名<input type="text" name="username" id="username" value="{{ username }}"><br>
    密码<input type="password" name="pwd" id="pwd"><br>
    <input type="checkbox" name='rem_name' id="rem_name"> 记住用户名<br>
    <input type="submit" value="登录"><br>
    <input type="button" value="ajax实现" id="ajaxBtn">
    <div id="loginmsg" style="display: none"></div>
</form>

</body>
</html>

templates/login_check.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    登录成功！
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<script src="/static/js/jquery-1.12.4.min.js"></script>

{#<style>#}
{#    #warn{#}
{#        display: none;#}
{#        color: red;#}
{#    }#}
{##}
{#</style>#}
{#<script>#}
{#    window.onload = function () {#}
{#        if({{ warn_data }}) {#}
{#        var Owarn = document.getElementById('warn')#}
{#            Owarn.style.display = 'block'#}
{#    }#}
{#    }#}
{#</script>#}

<script>
    $(function () {
        $("#ajaxBtn").click(function () {
            username = $("#username").val()
            pwd = $("#pwd").val()
            email = $("#email").val()
            phone = $("#phone").val()
            $.ajax({
                'url':'/register_check',
                'type':'post',
                'data':{'username':username,'pwd':pwd,'email':email,'phone':phone},
                'dataType':'json',
            })
        })
    })
</script>
<body>

<form action="/register_check" method="post">
    用户名<input type="text" name="username" id="username"><br>
    密码<input type="password" name="pwd" id="pwd"><br>
    email<input type="text" name="email" id="email"><br>
    手机<input type="text" name="phone" id="phone"><br>
    <input type="submit" value="注册"><br>
{#    <div id="warn">用户名重复</div>#}
    <input type="button" value="ajax实现" id="ajaxBtn">
</form>
</body>
</html>

templates/register_check.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    注册成功！
</body>
</html>

templates/show_msg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>展示信息</title>
</head>

<body>
    {% load filters %}
    <li>姓名：--  {{ username }}</li>
    <li>电话：--  {{ phone|modphone }}</li>
    <li>邮箱：--  {{ email|modemail }}</li>

</body>
</html>

templates/url_reverse.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<a href="/02">02</a>
url反向解析<br>
<a href="{% url 'booktest:02' %}">02反向</a><br>
<a href="{% url 'booktest:show_args' 3 2 %}">show</a>
<a href="{% url 'booktest:show_kwargs' c=3 d=4 %}">showkw</a>
</body>
</html>